services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    image: template-extensiones:latest
    container_name: template-extensiones
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
